[TPyNode]
logfile = /var/log/tpynode.log
pidfile = /var/run/tpynode.pid
module_path = /var/tpymodules/
host = 0.0.0.0
port = 42337
token = None

[OpenWrt]
module = OpenWrt

[WiGigIface]
interface = wlan2

[Hostapd]
interface = wlan2

[WPASupplicant]
interface = wlan2

[IPerf]
bin = iperf3
logfile = /var/log/iperf.log
port = 5201