[DEFAULT]
PORT = 42337
tmpdir = /tmp

[Node01]
host = 10.11.11.1
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node02]
host = 10.11.11.2
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node03]
host = 10.11.11.3
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node05]
host = 10.11.11.5
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node06]
host = 10.11.11.6
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node07]
host = 10.11.11.7
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node09]
host = 10.11.11.9
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node10]
host = 10.11.11.10
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node11]
host = 10.11.11.11
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node12]
host = 10.11.11.12
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node13]
host = 10.11.11.13
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node14]
host = 10.11.11.14
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node15]
host = 10.11.11.15
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node16]
host = 10.11.11.16
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node17]
host = 10.11.11.17
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node18]
host = 10.11.11.18
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node19]
host = 10.11.11.19
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

[Node20]
host = 10.11.11.20
conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf

#[Node24]
#host = 10.11.11.24
#conf = /usr/local/lib/python3.5/dist-packages/tpynode-0.0.0+98dc2d4-py3.5.egg/tpynode/data/rest_node.conf


